name: publish

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: fregante/setup-git-user@v1
      - run: echo git branch  
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm set "//registry.npmjs.org/:_authToken = ${{ secrets.NPM_AUTH_TOKEN }}"
      - run: npm install
      - run: npm run github-release
