name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - run: echo git branch  
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm set "//registry.npmjs.org/:_authToken = ${{ secrets.NPM_AUTH_TOKEN }}"
      - run: npm install
      - run: npm run github-release
